### ISSUE TITLE
Trying to use moveDelay on the click event

### ISSUE THREAD

**Issue by jameshooddisc** [Xetera/ghost-cursor#105]
Hi,

I'm trying to set different values to moveDelay option for the click event, and always getting same behaviour.

Tried with {moveDelay: 1500000} and acts as fast or slow as if i do with {moveDelay: 1}.

This value is supposed to be the time in ms until the promise on the await element.click() will be resolved, meaning the time that code will be stopped there after doing the click. Is this correct?

I'm running the version 1.1.18.

Thanks

**Comment by bvandercar-vt** [comment]
What you want is `moveSpeed`. Per the docs, `moveDelay` is the delay after a `click` or `move` occurs, ie a a delay before the next action.
