### ISSUE TITLE
How to stop random moves

### ISSUE THREAD

**Issue by AndriusCTR** [Xetera/ghost-cursor#113]
If I launch it with random moves enabled, and I need to stop those moves, perform manual movement, and continue random moves, how would I go about that?

let cursor = createCursor(page, await getRandomPagePoint(page), true);

// stop random moves, do other stuff

// continue random moves

**Comment by TheGP** [comment]
What do you mean? It automatically toggles it. Or you can probably call it manually like:
`cursor.toggleRandomMove(true);`

**Comment by AndriusCTR** [comment]
I mean what I wrote. I want to manually stop 'random moves process' and then manually restart it 20 lines later, etc.

**Comment by TheGP** [comment]
I mean what I wrote too, did u read it?

**Comment by AndriusCTR** [comment]
> I mean what I wrote too, did u read it?

Doesn't work for me. It does not stop anything. Random moves continue to move

**Comment by FreemanDan** [comment]
same

**Comment by FreemanDan** [comment]
> Doesn't work for me. It does not stop anything. Random moves continue to move
same

**Comment by TheGP** [comment]
Do it after every move or click.

**Comment by bvandercar-vt** [comment]
> Do it after every move or click.

This is the answer.

If this PR gets merged, should only have to set it where it needs to change: https://github.com/Xetera/ghost-cursor/pull/132

**Comment by AndriusCTR** [comment]
> Do it after every move or click.

What does that mean? I should repeatedly write cursor.toggleRandomMove(false) all over the code?

If I toggle it OFF then it should stay OFF until I toggle it on or script ends. Who came up with this nonsense logic?

**Comment by bvandercar-vt** [comment]
>  I should repeatedly write cursor.toggleRandomMove(false) all over the code?

With the way it's currently written, yes you have to. After every `move` or `click`. This PR  https://github.com/Xetera/ghost-cursor/pull/132 should fix this so you only have to set `cursor.toggleRandomMove` once, or as-needed.

The repo owner has been great about merging PRs so keep an eye on this one.

> Who came up with this nonsense logic?

Rude and unnecessary

**Comment by AndriusCTR** [comment]
> 
> > Who came up with this nonsense logic?
> 
> Rude and unnecessary

Necessary until they start thinking what they do and what they write.

**Comment by Niek** [comment]
Fixed in #132

**Comment by TheGP** [comment]
@AndriusCTR It is necessary for you to shut up and fix it urself.
P.S. This guy is complaining around, instead of helping.

**Comment by TheGP** [comment]
@bvandercar-vt much obliged, sir!
