### ISSUE TITLE
puppeteer: how to use with an iframe?

### ISSUE THREAD

**Issue by unixfox** [Xetera/ghost-cursor#14]
Currently, it's only possible to use it with an element that is on the page but not in an iframe.

When trying to pass the selector of an element in an iframe I get:
```
Error: Could not find element with selector "#recaptcha-anchor", make sure you're waiting for the elements with "puppeteer.waitForSelector"
```

**Comment by unixfox** [comment]
Sorry for the noise, I found how to do it. Just pass the element not the selector to cursor.click(), like this:
```js
const cursor = createCursor(page);
const checkbox = await frame.$('#element');
await cursor.click(checkbox);
```

**Comment by Niek** [comment]
That works indeed. BTW you can also use XPath instead of CSS selectors in case it's something more difficult to select.
