### ISSUE TITLE
Mouse movement cannot be simulated - it gets caught

### ISSUE THREAD

**Issue by zfcsoftware** [Xetera/ghost-cursor#145]
https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher
https://drissionpage.pages.dev/

Detected when not in use with the following code. Mouse screenX value is not updated. (Recaptcha v3 can detect it. https://antcpt.com/score_detector/)

```
    await page.evaluateOnNewDocument(() => {
        Object.defineProperty(MouseEvent.prototype, 'screenX', {
            get: function () {
                return this.clientX + window.screenX;
            }
        });

        Object.defineProperty(MouseEvent.prototype, 'screenY', {
            get: function () {
                return this.clientY + window.screenY;
            }
        });

    });
```

**Comment by Niek** [comment]
This is a known issue for a few years. It can be fixed in the de tools C++ code. It's outside the scope of ghost cursor.
