### ISSUE TITLE
How can i see the trace of mouse?

### ISSUE THREAD

**Issue by alanzed555** [Xetera/ghost-cursor#17]
I  want to see the trace of mousemove.How can i do?
thank u.

**Comment by Niek** [comment]
Here's some sample code:
```js
const { createCursor, getRandomPagePoint, installMouseHelper } = require('ghost-cursor');

const cursor = createCursor(page, await getRandomPagePoint(page), true);
await installMouseHelper(page); // this shows the trace
await cursor.click('element', { waitForMouse: 10000, waitForSelector: 1000, paddingPercentage: 20 });
```

**Comment by alanzed555** [comment]
> Here's some sample code:
> 
> ```js
> const { createCursor, getRandomPagePoint, installMouseHelper } = require('ghost-cursor');
> 
> const cursor = createCursor(page, await getRandomPagePoint(page), true);
> await installMouseHelper(page); // this shows the trace
> await cursor.click('element', { waitForMouse: 10000, waitForSelector: 1000, paddingPercentage: 20 });
> ```

thank u!
