### ISSUE TITLE
Sometimes Invalid parameters x: double value expected; y: double value

### ISSUE THREAD

**Issue by brunogaspar** [Xetera/ghost-cursor#2]
Hey, very randomly i receive this error and unfortunately i don't have a very good way to reproduce it.

Node: v10.16.3
Puppeteer: v2.1.1

I also use Puppeteer Extra Stealth and Ad Blocker plugins, although it does not seem to matter, i don't think :)

```js
(node:991) UnhandledPromiseRejectionWarning: Error: Protocol error (Input.dispatchMouseEvent): Invalid parameters x: double value expected; y: double value expected
    at /xxx/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/xxx/node_modules/puppeteer/lib/Connection.js:182:12)
    at Mouse.move (/xxx/node_modules/puppeteer/lib/Input.js:209:26)
    at Mouse.<anonymous> (/xxx/node_modules/puppeteer/lib/helper.js:112:23)
    at /xxx/node_modules/ghost-cursor/lib/spoof.js:146:43
    at step (/xxx/node_modules/ghost-cursor/lib/spoof.js:44:23)
    at Object.next (/xxx/node_modules/ghost-cursor/lib/spoof.js:25:53)
    at /xxx/node_modules/ghost-cursor/lib/spoof.js:19:71
    at new Promise (<anonymous>)
  -- ASYNC --
    at Mouse.<anonymous> (/xxx/node_modules/puppeteer/lib/helper.js:111:15)
    at /xxx/node_modules/ghost-cursor/lib/spoof.js:146:43
    at step (/xxx/node_modules/ghost-cursor/lib/spoof.js:44:23)
    at Object.next (/xxx/node_modules/ghost-cursor/lib/spoof.js:25:53)
    at /xxx/node_modules/ghost-cursor/lib/spoof.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/xxx/node_modules/ghost-cursor/lib/spoof.js:15:12)
    at tracePath (/xxx/node_modules/ghost-cursor/lib/spoof.js:134:49)
    at Object.<anonymous> (/xxx/node_modules/ghost-cursor/lib/spoof.js:213:40)
    at step (/xxx/node_modules/ghost-cursor/lib/spoof.js:44:23)
(node:991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Snippet of my code:

```js
...

this.page = await this.browser.newPage()

this.cursor = createCursor(this.page)
...

await this.page.waitForSelector('[data-owl-labels]')
await this.cursor.click('[data-owl-labels]')


await this.page.waitForSelector('#searchTerm_Header')
await this.cursor.move('#searchTerm_Header')
```

Thanks and let me know if there's anything i can do to help on fixing the bug :)

**Comment by Xetera** [comment]
This seems fairly difficult to fix, can you tell me which pages you're getting this error in? Is it random or does it happen on specific elements?

I have a feeling this might be caused by the library not being able to find the dimensions of an element :thinking: I might have to make it fallback to just clicking the element. Always helps to be able to reproduce it though

**Comment by brunogaspar** [comment]
> This seems fairly difficult to fix, can you tell me which pages you're getting this error in? Is it random or does it happen on specific elements?

Yup, i know.

It happens very randomly therefore, unfortunately, i don't have any good way to reproduce.

I'll try to see if i can figure out a pattern when this happens as my suspicion is that, since i have a page i'm going to, then i apply a not higher timeout, it might happen that whenever the cursor.move gets executed, that specific element might not be on the screen yet.

I've wrapped the above in try/catch blocks for now so it doesn't stop execution.

**Comment by Niek** [comment]
+1 - I sometimes see this issue happening as well

**Comment by Niek** [comment]
I don't see this happening anymore after https://github.com/Xetera/ghost-cursor/pull/8 was merged. @brunogaspar can you check (use `yarn add Xetera/ghost-cursor#master`)?

**Comment by brunogaspar** [comment]
Don't have time right now unfortunately, but i trust your evaluation :)
