### ISSUE TITLE
clickCount support

### ISSUE THREAD

**Issue by NikolaiT** [Xetera/ghost-cursor#20]
hey guys, thanks for the awesome module.

Please support click optinos like that:

```JavaScript
  const cursor = createCursor(page);

  await cursor.click('.someClass', {clickCount: 3})
```

Thanks

**Comment by Xetera** [comment]
Seems like something you can just do in a for loop, is there a reason why this is necessary?

**Comment by Niek** [comment]
Yeah, this seems a bit unnecessary to me.

**Comment by NikolaiT** [comment]
Not really necessary, but would remain compatible with the interface of pptr. Maybe there are more clickoptions?
