### ISSUE TITLE
Iframe error

### ISSUE THREAD

**Issue by DrewDaPilot** [Xetera/ghost-cursor#22]
``Error: Protocol error (DOM.scrollIntoViewIfNeeded): Node does not have a layout object
    at C:\Users\Drew\WebstormProjects\project\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Drew\WebstormProjects\project\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at Object.<anonymous> (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:373:53)
    at step (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:44:23)
    at Object.next (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:25:53)
    at C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:15:12)
    at Object.move (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:332:20)

C:\Users\Drew\WebstormProjects\project>
``

As you can see, the error indicates that something is wrong with the code that attempts to scroll the element into view. Here is the code I used:

`` 
    const page = (await browser.pages())[0];
    const cursor = createCursor(page);

    await page.goto('file://C:/Users/Drew/WebstormProjects/project/index.html');

    await page.waitForSelector("iframe");
    const frame = await (await page.$("iframe")).contentFrame();

    await frame.waitForSelector(".checkbox");
    const checkbox = await frame.$(".checkbox");

    console.log("Found checkbox!");
    await cursor.click(checkbox);
    console.log("Clicked checkbox!");
``

**Comment by Niek** [comment]
I just pushed v1.1.4 that should fix this, please check & confirm.

**Comment by DrewDaPilot** [comment]
Thanks! I ran it again and got a different error.

`
C:\Users\Drew\WebstormProjects\project>node index.js
Found checkbox!
C:\Users\Drew\WebstormProjects\project\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (DOM.getContentQuads): Could not compute content quads.
    at C:\Users\Drew\WebstormProjects\captcha-assassin\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Drew\WebstormProjects\project\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:118:45
    at step (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:44:23)
    at Object.next (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:25:53)
    at C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:15:12)
    at getElementBox (C:\Users\Drew\WebstormProjects\project\node_modules\ghost-cursor\lib\spoof.js:109:12)

C:\Users\Drew\WebstormProjects\project>
`

**Comment by Niek** [comment]
Can you please share the exact code including the HTML example with me?

**Comment by DrewDaPilot** [comment]
Sure,

`const puppeteer = require('puppeteer-extra');
const { createCursor } = require("ghost-cursor");
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}


puppeteer.launch(
    {
        headless: false,
        args: [
            '--disable-web-security',
            '--disable-features=IsolateOrigins,site-per-process'
        ]
    }).then(async browser => {
    const page = (await browser.pages())[0];
    const cursor = createCursor(page);

    await page.goto('file://C:/Users/Drew/WebstormProjects/captcha-assassin/index.html');

    await page.waitForSelector("iframe");
    const frame = await (await page.$("iframe")).contentFrame();

    await frame.waitForSelector(".checkbox");
    const checkbox = await frame.$(".checkbox");

    console.log("Found checkbox!");
    await cursor.click(checkbox);
    console.log("Clicked checkbox!");
});

`

where index.html is

`<html>
    <head>
        <script src="https://hcaptcha.com/1/api.js" async defer></script>
    </head>
    <body>
        <div class="h-captcha" data-sitekey="f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34"></div>
    </body>
</html>`

**Comment by Niek** [comment]
The problem is that the frame is getting detached, see this (slightly rewritten code):

```typescript
import puppeteer from 'puppeteer'
import { createCursor, getRandomPagePoint, installMouseHelper } from 'ghost-cursor'

(async () => {
  const browser = await puppeteer.launch({ headless: false, defaultViewport: null })
  const page = await browser.newPage()
  const cursor = createCursor(page, await getRandomPagePoint(page), true)
  await installMouseHelper(page)
  await page.goto('file:///path/to/test.html')
  const frame = await (await page.waitForSelector('iframe')).contentFrame()
  if (frame != null) {
    const checkbox = await frame.waitForSelector('.checkbox')
    if (checkbox != null) {
      await cursor.click(checkbox)
    }
  }
})()
```
Result: `waitTask.terminate(new Error('waitForFunction failed: frame got detached.'));`

**Comment by DrewDaPilot** [comment]
Ah, so its not a problem with the lib. Thanks for the assistance, I guess I can close this issue.
