### ISSUE TITLE
Delay of cusor.click()

### ISSUE THREAD

**Issue by Nevgup** [Xetera/ghost-cursor#24]
Hello !

When I use cursor.click(element) and then make a page.keyboard.type(), there is a delay between the click and the first keystroke. How can I reduce the click delay please ?

Thanks !

**Comment by Niek** [comment]
Hello, this is the line in question:
https://github.com/Xetera/ghost-cursor/blob/3c3b4ab9f8f0f6103d64f4e64f3218313c448c63/src/spoof.ts#L209
If you want to create a PR to make this an option, you're welcome :)

**Comment by Nevgup** [comment]
I'll try to make it soon, thanks for the help ! :)
