### ISSUE TITLE
Separate vertical and horizontal padding

### ISSUE THREAD

**Issue by smokierobinson** [Xetera/ghost-cursor#29]
First of all, many thanks for creating this package! It has really helped my project a lot.
I am using the cursor mainly for clicking tens of elements on a page in succession and I have noticed that using `paddingPercentage` produces several misclicks. After watching puppeteer running without headless mode I suspect that the reason is that the cursor clicks too low or too high vertically. 
So my feature request is to introduce separate vertical and horizontal padding percentages, something like:
```
..., paddingPercentage: {vertical: 5, horizontal: 10} 
``` 
or
```
..., paddingPercentage: [5,10]
```

**Comment by Niek** [comment]
There is already a `paddingPercentage` option to add padding on the top/bottom and left/right. It would be possible to split those up but that would complicate the code quite a bit. If you have a clean approach (without adding yet another option) please let me know and I'll look at it.
