### ISSUE TITLE
Is it possible to add work with an element directly?

### ISSUE THREAD

**Issue by ergcode** [Xetera/ghost-cursor#3]
/src/spoof.ts
```  const actions = {
    async click(selector: any) {
      if (selector) {
        await actions.move(selector);
      }
      return page.mouse.down().then(() => page.mouse.up());
    },
    async move(selector: any) {
			const elem = (typeof selector === 'string')
				? await page.$(selector)
				: await selector;
      if (!elem) {```


Example: 
```
		let cursor = createCursor(page);
		await page.goto(
			'https://infosimples.github.io/detect-headless/', {
			waitUntil: ['domcontentloaded'],
			30000,
		});

		let select = await page.$('#mouse-move-result');
		await cursor.move(select);
		select = await page.$('#plugins-prototype-result');
		await cursor.move(select);
		await cursor.click(select);
```

What for? There is a case when elements are enumerated, for example, a form with data.
And it’s not always possible to precisely bind to an element selector.

**Comment by kekearif** [comment]
Bump. I have multiple buttons with the same selector on a page. I need to iterate them and click them. Is this at all possible with `ghost-cursor` ?

**Comment by Niek** [comment]
Fixed in https://github.com/Xetera/ghost-cursor/pull/10 - support for XPath added.

BTW, if you want to use CSS selectors you can also use `nth-child()` pseudo selectors: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child
