### ISSUE TITLE
Playwright support ?

### ISSUE THREAD

**Issue by thibaultmthh** [Xetera/ghost-cursor#36]
is a support for playwright planned ?

**Comment by Niek** [comment]
It shouldn't be too hard to support. In addition, native CDP support would be great as well - I'll look into this soon.

**Comment by Niek** [comment]
OK, I take that back 🙈 It's extremely hard to support both Puppeteer and Playwright, there are too many subtle differences, missing classes, etc. I recommend to take this approach (which you can use in native CDP too):

```js
const { path } = require('ghost-cursor');

for (const pos of path({x: 0, y: 0}, {x: _x, y: _y})) {
  // Playwright:
  //await mouse.move(pos.x, pos.y);

  // CDP:
  await Input.dispatchMouseEvent({ x: pos.x, y: pos.y, type: 'mouseMoved' });
}
```

Closing this ticket for now.

**Comment by galaczi** [comment]
It's probably a lot of work too, but if you make a [puppeteer-extra](https://github.com/berstend/puppeteer-extra) plugin, as far as I know the automation layer supports both Puppeteer and Playwright. Any chance of that?

**Comment by Xetera** [comment]
I believe the puppeteer-extra team is already working on a plugin inspired by this library. You could probably use that instead
