### ISSUE TITLE
Start position is always 0,0

### ISSUE THREAD

**Issue by excelant100** [Xetera/ghost-cursor#38]
The Start position of cursor.move or click is always 0,0. I want to randomize this, where can I set that? 

I tried to page.mouse.move to a random coordinates, but since I am scrolling. The movement done by page.mouse is useless and the cursor spawns back to 0,0.

**Comment by Niek** [comment]
You can use this function for that:
https://github.com/Xetera/ghost-cursor/blob/2a7ac70027c0beaece6929904ca1264e0cff4a06/src/spoof.ts#L46-L50
