### ISSUE TITLE
Slow down cursor speed

### ISSUE THREAD

**Issue by RobinFrcd** [Xetera/ghost-cursor#44]
Hello,
Thank you for this great module, very useful !

I think that, in some situations, the cursor is really going too fast. Would it be possible to add a `moveDuration` option to the `click`/`move` functions ?

Thanks !

**Comment by RobinFrcd** [comment]
Just realized a [PR](https://github.com/Xetera/ghost-cursor/pull/43) was already on the go ! Any chance it'll be merged soon ? :pray:

**Comment by trompx** [comment]
Would also like to see this merged.

**Comment by Niek** [comment]
Fixed in #43
