### ISSUE TITLE
Sometimes misses element

### ISSUE THREAD

**Issue by SmartArray** [Xetera/ghost-cursor#49]
I can't reproduce it, but I have seen this library missing an element. The click apparently hit another element next to it. 99% of the time it seems to work though.

**Comment by Niek** [comment]
Hmm, that will be very hard to reproduce... it could be anything from a jumping element on the page, to the click not properly being registered through CDP.

**Comment by natanavra** [comment]
+1

**Comment by paulosllvn** [comment]
+1, going to have to move away from this as it's a little bit unrealiable for me. It sometimes misses the input box for a login as part of my puppeteer bot.

For reference I am trying to login to www.betfair.com.au. Sometimes it will miss one of these inputs and fail to login forcing me to restart my bot. 

I am targetting 

'//input[@id="ssc-liu"]'  and  '//input[@id="ssc-lipw"

**Comment by Niek** [comment]
I still haven't been able to reproduce this reliably. I wonder if it's an actual bug or if the element is shifted last-second before the click. Do you see a difference when using a different value for `paddingPercentage`?

**Comment by paulosllvn** [comment]
> I still haven't been able to reproduce this reliably. I wonder if it's an actual bug or if the element is shifted last-second before the click. Do you see a difference when using a different value for `paddingPercentage`?

Try running this a few hundred times. Sometimes it will miss the input boxes.

`let loginBetFair = async (page: puppeteer.Page) => {
    const URL = "https://www.betfair.com.au"
    await page.setViewport({
        width: 1280, height: 800,
        deviceScaleFactor: 1,
    });
    const cursor = createCursor(page)
    await page.goto(URL, {waitUntil: 'networkidle2'});
    await sleep_for(page, 3000, 5000);
    await enterUserDetailsNoCursor(page, '//input[@id="ssc-liu"]', '//input[@id="ssc-lipw"]', username, betfairPassword)
    await page.waitForTimeout(1000);
    const loginBtn = await page.$x('//input[@id="ssc-lis"]');
    await cursor.click(loginBtn[0]);
    await sleep_for(page, 500, 2000);
}

//Ghost Cursor
let enterUserDetails = async (page: puppeteer.Page, cursor: GhostCursor, userSpecifier: string, passwordSpecifier: string, username: string, password: string) => {
    await page.waitForTimeout(4000);
    const usernameInput = await page.$x(userSpecifier)
    await cursor.click(usernameInput[0])
    await page.keyboard.type(username);
    const passwordInput = await page.$x(passwordSpecifier);
    await cursor.click(passwordInput[0])
    await page.keyboard.type(password);
}
`
