### ISSUE TITLE
How does installMouseHelper work ?

### ISSUE THREAD

**Issue by CarmenLexa** [Xetera/ghost-cursor#50]
I am using the module, but I don't know how certain functions like installMouseHelper work, what does it do?
What is the difference between move and moveTo? 
I tried to leave a donation but I don't see that you have a link :=

**Comment by Niek** [comment]
The `installMouseHelper()` function adds a quick overlay over the page showing where the mouse is moving and when it's clicking. See https://github.com/Xetera/ghost-cursor/issues/13#issuecomment-780440923 for some sample code.

The difference between the `move()` and `moveTo()` are obvious from the signatures:
```ts
  move: (selector: string | ElementHandle, options?: MoveOptions) => Promise<void>
  moveTo: (destination: Vector) => Promise<void>
```
So normally you'll use `move()`.

BTW we really need some proper documentation, if you can help with a PR to improve that that would be greatly appreciated.
