### ISSUE TITLE
its not work

### ISSUE THREAD

**Issue by IgalNeeman** [Xetera/ghost-cursor#51]
i was installed this but its not work

anybody help with this ?

i have 3 years experince with puppeteer

**Comment by Niek** [comment]
Please elaborate what is not working with a reproducible script.

**Comment by IgalNeeman** [comment]
i cant load the script to use it with puppeteer...
its not working

‫בתאריך יום א׳, 24 באפר׳ 2022 ב-21:49 מאת ‪Niek van der Maas‬‏ <‪
***@***.***‬‏>:‬

**Comment by Niek** [comment]
> i cant load the script to use it with puppeteer... its not working

Do you have a reproducible script? Otherwise I have to close this issue.

**Comment by IgalNeeman** [comment]
YOU CAN CLOSE I DELETE YOUR SCRIPT
BECAUSE WE CANT LOAD THIS WITH PUPPETEER ITS NOT WORKED

‫בתאריך יום א׳, 24 באפר׳ 2022 ב-22:47 מאת ‪Niek van der Maas‬‏ <‪
***@***.***‬‏>:‬
