### ISSUE TITLE
 commonjs, es5 version aviable?

### ISSUE THREAD

**Issue by lashki** [Xetera/ghost-cursor#52]
Hi,
 is there a way to use ghost cursor with common.js, require statement?

**Comment by Niek** [comment]
Sure:
```js
const { createCursor } = require('ghost-cursor')
```

**Comment by lashki** [comment]
Thanks a lot. I was banging my head on the wall for the past week with this issue potential workarounds. Now you solved the situation... A small advice: maybe it will be good to include this in the instructions... Thanks again.

**Comment by Niek** [comment]
No problem - there definitely needs to be some updated docs, see also https://github.com/Xetera/ghost-cursor/issues/13
