### ISSUE TITLE
[Question] Was `default-human-emulator` inspired by `ghost-cursor`, or the other way around?

### ISSUE THREAD

**Issue by DannyEndert** [Xetera/ghost-cursor#55]
Was `default-human-emulator` inspired by `ghost-cursor`, or the other way around?

https://github.com/ulixee/secret-agent/blob/a4a93b4f3e93cc9ab2616084b46803bcb7e517d2/plugins/default-human-emulator/generateVector.ts

Purely out of interest.

**Comment by Niek** [comment]
The former, the original version was even called `emulate-humans-ghost`.
