### ISSUE TITLE
[Question] Are "MouseEvents" the same as a real, physical mouse movement?

### ISSUE THREAD

**Issue by 0x7357** [Xetera/ghost-cursor#56]
I have problems with the offsets etc. (address bar, tabs bar, etc.) and therefore wonder if MouseEvents are the same as real, physical mouse movements or if programmatic mouse movements are recognizable as "programmatic"?

**Comment by Niek** [comment]
@DannyEndert there should be no difference between the mouse events generated by the CDP protocol (`Input.dispatchMouseEvent()`) and human mouse events. For example, they both have `isTrusted: true`, while a manually created event shows this property as `false`.
