### ISSUE TITLE
Found a lot of issues

### ISSUE THREAD

**Issue by vladtreny** [Xetera/ghost-cursor#58]
Finally reached this library and tested on many sites, a lot of issues, despite great idea

Also, this one is better for example  {behavior: 'smooth', block: 'center'}

Possible to rewrite it for isolated-worlds?   

I see a possibility to do it the code

**Comment by Niek** [comment]
Feel free to make a PR 👍🏻

**Comment by vladtreny** [comment]
Just change to {behavior: 'smooth', block: 'center'} in the spoof js 
This one just spotted

I will be rewriting it for custom usage with iso worlds   Seems like easier

**Comment by vladtreny** [comment]
another problem (in puppeteer in general)  if element is hovered by another one, or there is overlay or Reach changes the element very fast   it will not  work.     I fixed it in my implementation though    

anyway great work, a lot of good ideas.  thank you

**Comment by vladtreny** [comment]
ps in one anti vendor just found a possibility to detect it 

probably need a complete rewrite  :(

**Comment by vladtreny** [comment]
Can check on NuData.  Mediocre provider, but mouse checker is good
