### ISSUE TITLE
Cursor seems to overshoot a little too much sometimes

### ISSUE THREAD

**Issue by kekearif** [Xetera/ghost-cursor#6]
I have noticed that occasionally the cursor will overshoot a little too much and not click the element. This is causing puppeteer's to accidentally navigate to the wrong page.

Is the a way to adjust the overshoot and make it smaller?

**Comment by Niek** [comment]
This should be fixed with the new `paddingPercentage` option - you can now set the padding to e.g. 20 and it will choose a random point within 20% of the width and height of the element.
