### ISSUE TITLE
Cursor Movement and Clicking Not Working For Any Selectors

### ISSUE THREAD

**Issue by TrustyJar** [Xetera/ghost-cursor#65]
This is the example of the error that I get 

`Warning: could not move mouse, error message: ProtocolError: Protocol error (Input.dispatchMouseEvent): Invalid parameter`
`Invalid parameters`

I can confirm that the selectors I am using are valid. I haven't been getting this problem only until recently. Haven't changed anything up so I am a bit confused why it is happening

**Comment by TrustyJar** [comment]
Nevermind, after an hour of searching I somehow found the issue. For some reason this package doesn't work with puppeteer-core. Not sure why, I will look into it and possibly make a pr

**Comment by hackermondev** [comment]
Experiencing same issue but I'm using ``puppeteer-extra``

**Comment by hackermondev** [comment]
I had to create the cursor after the element was loaded to fix it.

**Comment by TrustyJar** [comment]
> I had to create the cursor after the element was loaded to fix it.

So you have to create a new cursor variable every time you switch pages? You should only have to define cursor one time throughout your script.
