### ISSUE TITLE
Falling back to JS scroll method TypeError: page._client.send is not a function

### ISSUE THREAD

**Issue by firmart** [Xetera/ghost-cursor#67]
Since puppeteer 13.6.0, the correct way to create a CDP session client is 

```js
const client = await page.target().createCDPSession();
```
Related: #61 

See 
- https://puppeteer.github.io/pptr.dev/#?product=Puppeteer&version=v13.6.0&show=api-class-cdpsession
- https://github.com/puppeteer/puppeteer/blob/v15.3.0/docs/api/puppeteer.cdpsession.md

**Comment by Niek** [comment]
Are you using the latest version? We have this fix in place to prevent this issue:
https://github.com/Xetera/ghost-cursor/blob/7327dfa3215e6f2a9391af650ff2221c2e4dfe80/src/spoof.ts#L85

**Comment by firmart** [comment]
I have seen this line but didn't update to the latest. Now, updated to the latest version (i.e. from `1.1.8` to `1.1.15`), I got another error: 
```shell
TypeError: elem.remoteObject is not a function
    at Object.<anonymous> (/node_modules/ghost-cursor/lib/spoof.js:458:61)
    at step (/node_modules/ghost-cursor/lib/spoof.js:44:23)
    at Object.next (/node_modules/ghost-cursor/lib/spoof.js:25:53)
    at fulfilled (/node_modules/ghost-cursor/lib/spoof.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
``` 
BTW, any reason to access internal field like `_client` instead of the aforementioned `const client = await page.target().createCDPSession()` ?

**Comment by Niek** [comment]
Can you share the snippet where you get the `remoteObject` error @firmart?

The reason we don't use `createCDPSession()` is that it opens an additional CDP session instead of using the existing session, i.e. extra overhead.

**Comment by Niek** [comment]
Closing for now - if you get the `remoteObject` error, please open a new issue @firmart
