### ISSUE TITLE
Generating a route using path() which includes overshoot coordinates 

### ISSUE THREAD

**Issue by CJ13th** [Xetera/ghost-cursor#68]
I really like the implementation of this project but I'm not keen on using Puppeteer to automate the browser since many companies claim to be able to detect its use. The path function seems very useful for generating the necessary coordinates for mouse movement, are there any plans to include the overshoot functionality?

**Comment by Niek** [comment]
You can call the `path()` function and get the `Vector[]` back, which you can use to directly steer CDP (e.g. using `Input.dispatchMouseEvent()`.

**Comment by CJ13th** [comment]
Thanks, this is what I'm planning on doing, but I really liked the idea of the overshoot-then-correct functionality which seems to come with puppeteers `cursor.move()`. Unless I'm mistaken, the `Vector[]` returned by `path` just doesn't include overshoot coordinates so I just wanted to check if there were plans to include this?

**Comment by Niek** [comment]
True, the overshooting is not contained in `path()` but is rather trivial to implement, see the following code:
https://github.com/Xetera/ghost-cursor/blob/7327dfa3215e6f2a9391af650ff2221c2e4dfe80/src/spoof.ts#L354-L370
