### ISSUE TITLE
what does waitForMouse option do and which file can i find its reference/where its defined? since when i search through this repository, it doesnt show where it is defined

### ISSUE THREAD

**Issue by EVE231** [Xetera/ghost-cursor#69]
since when i search through this repository, none of the files show where it is defined. I don't want to miss out on options available that could help me.

**Comment by Niek** [comment]
There is no `waitForMouse`, only `waitForClick` and `waitForSelector`.

**Comment by EVE231** [comment]
ok because it was referenced here https://github.com/Xetera/ghost-cursor/issues/17#issuecomment-755995616 which is why I was curious
