### ISSUE TITLE
How to increase mouse speed for moveTo method?

### ISSUE THREAD

**Issue by EVE231** [Xetera/ghost-cursor#70]
await cursor.moveTo(await ghostCursor.getRandomPagePoint(page));    This takes extremely long for the mouse to move to the point on page. How can i increase the speed or what are my other options to make the cursor move faster to a specific vector point because cursor.move() method only accepts selector arguments  and not the specific vector point

**Comment by iamoskvin** [comment]
I have the same question. Do you find any solution?
The mouse speed is lower than I need.
I can manually edit the path function, but the maximum speed is 1, as I understood. How could I increase speed even more?
Thank you.

**Comment by Niek** [comment]
Fixed in #133

**Comment by ramsestom** [comment]
What is the unit of this moveSpeed parametter? Is it in pixels/ms or something else?

**Comment by bvandercar-vt** [comment]
> What is the unit of this moveSpeed parametter? Is it in pixels/ms or something else?

Issue: https://github.com/Xetera/ghost-cursor/issues/125
