### ISSUE TITLE
add a real mouse cursor

### ISSUE THREAD

**Issue by lublak** [Xetera/ghost-cursor#71]
It would be nice if the library would also show a real mouse cursor.
![image](https://user-images.githubusercontent.com/44057030/192460485-68e1e94d-f818-47b4-b091-a72e21a18dec.png)
![image](https://user-images.githubusercontent.com/44057030/192460518-48297857-d4b8-40d7-8d1e-b03567d97f9a.png)
![image](https://user-images.githubusercontent.com/44057030/192460542-c75e3205-4b80-4afa-9164-88f74be991d1.png)
etc.

**Comment by Niek** [comment]
This is possible by using the mouse helper, see https://github.com/Xetera/ghost-cursor/issues/13#issuecomment-780440923 for an example.

**Comment by Niek** [comment]
Why would you ever need that? It's an automation library, you're not even supposed to look at the mouse except for debugging purposes. Any CSS-animated mouse that is injected is detectible in the DOM as well, so I would highly recommend not to use that in production.

**Comment by lublak** [comment]
@Niek To create a reprdouble video with https://github.com/prasanaworld/puppeteer-screen-recorder. Sure with the dot it also works. 
I often have the problem that I always have to record the same thing (only with different elements).
I use pupeeteer to record this. This all works great. With ghot curosr I wanted to animate the cursor better now. Sure with the dot you can see it. Doesn't look quite as "nice" of course. Where I think that is a matter of taste.
