### ISSUE TITLE
Can post an example?

### ISSUE THREAD

**Issue by thorn5918** [Xetera/ghost-cursor#76]
[https://camo.githubusercontent.com/18b64308bb2cbf8fefba480ae90b0bb38add9bf6d7d3cb6c1886998e1160dfad/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3431383639393338303833333634383634342f3636343131303638333035343533383737322f6163635f67656e2e676966](url)

@Xetera @Niek 

Many thanks

**Comment by thorn5918** [comment]
![ghost-cursor in action](https://cdn.discordapp.com/attachments/418699380833648644/664110683054538772/acc_gen.gif)

**Comment by Niek** [comment]
Not an issue - closing
