### ISSUE TITLE
elem.remoteObject is not a function

### ISSUE THREAD

**Issue by lelly8484** [Xetera/ghost-cursor#83]
Keep getting this for line host-cursor\lib\spoof.js:475:61)

var elements = await page.$x('//*[@id=\"email[objectobject]__input\"]');
await cursor.click(elements[0]);

**Comment by Niek** [comment]
What version of Puppeteer are you using?

**Comment by lelly8484** [comment]
Oh i updated and it worked

**Comment by clouedoc** [comment]
I've got the same issue and upgrading puppeteer didn't work.
I also needed to upgrade puppeteer-core, which was not present in my `package.json`.

```bash
npm i puppeteer
npm i puppeteer-core
```
