### ISSUE TITLE
How to perform `press and hold` actions

### ISSUE THREAD

**Issue by icesmartjuan** [Xetera/ghost-cursor#95]
Hi expert, 

It's great to have such lib, would like to know how to perform `press and hold` actions ?  Thanks 
normally, we could do it via following code, but it seems not work in cursor. 
``` await page.click (selector, {delay: 10000});```

**Comment by Niek** [comment]
You can simply `.move()` to a specific selector, then use the `await page.click(selector, {delay: 10000})` click command as usual.
