### ISSUE TITLE
Usage of puppeteer-core with ghost-cursor

### ISSUE THREAD

**Issue by photorealisticbeaver** [Xetera/ghost-cursor#97]
Starting on puppeteer 19, PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true seems to be ignored, so it would be quite handy to be able to use puppeteer-core with ghost-cursor

**Comment by alvinlys** [comment]
```
import puppeteer from 'puppeteer-core'
import ghostCursor from 'ghost-cursor'

(async () => {
    const browser = await puppeteer.connect({
        browserURL,
    })
    const [page] = await browser.pages()
    const cursor = ghostCursor.createCursor(page)

    await cursor.click(selector)
})();
```

perhaps try this ^ ?

**Comment by Niek** [comment]
I think the env variables is now `PUPPETEER_SKIP_DOWNLOAD=1`.

As for puppeteer-core, it should work as well.
