### ISSUE TITLE
Usage of ghost-cursor with chrome-extension

### ISSUE THREAD

**Issue by montovaneli** [Xetera/ghost-cursor#98]
Hello!

Is there any way to use the ghost-cursor in a Chrome extension? I tried using the createCursor() method, but it requires a Puppeteer page.
My goal is to receive a URL via WebSocket, open it in a new tab, and simulate a human click on a button in that new tab.

**Comment by Xetera** [comment]
You can't control the exact mouse movements in client side Javascript without CDP or some kind of browser automation with an interface for it

**Comment by Lemon72476** [comment]
Did
